// Single data-access layer. Partners + events are bundled from the repo-root data/
// folder (generated by scripts/fetch-partners.mjs + scripts/build-events.mjs); the
// matching config from config/matching.json. Allocations are computed once at load.
import matchingConfig from "@config/matching.json";
import partnersData from "@data/partners.json";
import eventsData from "@data/events.json";
import { allocateCycle } from "./lib/matching.js";

export const config = matchingConfig;

export const partners = partnersData.partners;
export const partnersMeta = partnersData._meta;
export const events = eventsData.events;
export const eventsMeta = eventsData._meta;

export const partnersById = Object.fromEntries(partners.map((p) => [p.id, p]));
export const eventsById = Object.fromEntries(events.map((e) => [e.id, e]));

// Time-phased allocation: partners' capacity is shared across same-date events.
const cycle = allocateCycle(events, partners, config);
export const allocations = cycle.allocations;
export const partnerLoad = cycle.partnerLoad;
export const cycleSummary = cycle.summary;

// True when partners came from the synthetic fallback (Overpass unreachable at build).
export const usingFallback = partnersMeta.mode === "fallback";

// Every (event, partner) pair the engine proposed — the basis of the confirmations list.
export function proposedPairs() {
  const out = [];
  for (const e of events) {
    for (const a of allocations[e.id].assignments) {
      out.push({ eventId: e.id, partnerId: a.partnerId, meals: a.meals, source: "allocation" });
    }
  }
  return out;
}
